apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  version: the-ufile-part
  owner: umer

configMapGenerator:
- name: index.php
  files:
  - index.php


resources:
- base
