apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        envFrom:
          - configMapRef:
              name: index.php
      volumeMounts:
      - mountPath: /var/www/html
        name: index.html
    volumes:
    - name: index.html
      emptyDir: {}
